### ISSUE TITLE
Typescript support.

### ISSUE THREAD

**Issue by ketan-10** [abhinavxd/Draw-and-guess-game#19]
**Typescript advantages:** 
1) Compile time type checking support.
2) Early spotted bugs
3) Rich IDE support
4) Easy to scale and Improve Readability 
5) one more point to add in CV 😁

**Typescript disadvantages:** 
1) More boilerplate code code.
2) Difficult for newcomers

Typescript migration is very easy and incremental (per file basis), 
No existing logic need to change.

Open for discussion.

**Comment by abhinavxd** [comment]
This project is very small, and there are other issues that could be given more priority.
What do you say?
